# WAVE configuration file

# This stores sensitive information (decrypted graph nodes)
# and should only be readable by the user WAVE runs as
database = "/var/lib/wave/db"
# This should ideally be below 1000 to prevent a non root service
# from binding to this port
listenIp = "127.0.0.1:777"

[storage]
  # This is the in-memory HTTP server
  [storage.inmem]
  provider = "http_v1"
  url = "http://localhost:8001"
  version = "1"
